# https://hub.docker.com/_/microsoft-mssql-server?tab=description
# https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-docker-container-deployment?view=sql-server-ver15&pivots=cs1-bash
# https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15
# https://www.red-gate.com/simple-talk/databases/sql-server/tools-sql-server/sql-server-sqlcmd-basics/
# https://www.sqlshack.com/working-sql-server-command-line-sqlcmd/

FROM mcr.microsoft.com/mssql/server:2019-latest
