// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: EmployeeService.proto
#ifndef GRPC_EmployeeService_2eproto__INCLUDED
#define GRPC_EmployeeService_2eproto__INCLUDED

#include "EmployeeService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace HyperNovaLabs {
namespace Api {
namespace Protos {
namespace Services {

class EmployeeService final {
 public:
  static constexpr char const* service_full_name() {
    return "HyperNovaLabs.Api.Protos.Services.EmployeeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>> AsyncListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>>(AsyncListEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>> PrepareAsyncListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>>(PrepareAsyncListEmployeeRaw(context, request, cq));
    }
    virtual ::grpc::Status GetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Models::Employee* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Employee>> AsyncGetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Employee>>(AsyncGetEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Employee>> PrepareAsyncGetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Employee>>(PrepareAsyncGetEmployeeRaw(context, request, cq));
    }
    virtual ::grpc::Status CreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>> AsyncCreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>>(AsyncCreateEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>> PrepareAsyncCreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>>(PrepareAsyncCreateEmployeeRaw(context, request, cq));
    }
    virtual ::grpc::Status UpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>> AsyncUpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>>(AsyncUpdateEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>> PrepareAsyncUpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>>(PrepareAsyncUpdateEmployeeRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>> AsyncDeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>>(AsyncDeleteEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>> PrepareAsyncDeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>>(PrepareAsyncDeleteEmployeeRaw(context, request, cq));
    }
    virtual ::grpc::Status ListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>> AsyncListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>>(AsyncListOfAnEmployeeBillsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>> PrepareAsyncListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>>(PrepareAsyncListOfAnEmployeeBillsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Models::Employee* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Models::Employee* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void UpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* AsyncListEmployeeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* PrepareAsyncListEmployeeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Employee>* AsyncGetEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Employee>* PrepareAsyncGetEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* AsyncCreateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* PrepareAsyncCreateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* AsyncUpdateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* PrepareAsyncUpdateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* AsyncDeleteEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* PrepareAsyncDeleteEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* AsyncListOfAnEmployeeBillsRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* PrepareAsyncListOfAnEmployeeBillsRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>> AsyncListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>>(AsyncListEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>> PrepareAsyncListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>>(PrepareAsyncListEmployeeRaw(context, request, cq));
    }
    ::grpc::Status GetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Models::Employee* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Employee>> AsyncGetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Employee>>(AsyncGetEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Employee>> PrepareAsyncGetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Employee>>(PrepareAsyncGetEmployeeRaw(context, request, cq));
    }
    ::grpc::Status CreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>> AsyncCreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>>(AsyncCreateEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>> PrepareAsyncCreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>>(PrepareAsyncCreateEmployeeRaw(context, request, cq));
    }
    ::grpc::Status UpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>> AsyncUpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>>(AsyncUpdateEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>> PrepareAsyncUpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>>(PrepareAsyncUpdateEmployeeRaw(context, request, cq));
    }
    ::grpc::Status DeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>> AsyncDeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>>(AsyncDeleteEmployeeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>> PrepareAsyncDeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>>(PrepareAsyncDeleteEmployeeRaw(context, request, cq));
    }
    ::grpc::Status ListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>> AsyncListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>>(AsyncListOfAnEmployeeBillsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>> PrepareAsyncListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>>(PrepareAsyncListOfAnEmployeeBillsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response, std::function<void(::grpc::Status)>) override;
      void ListEmployee(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Models::Employee* response, std::function<void(::grpc::Status)>) override;
      void GetEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Models::Employee* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response, std::function<void(::grpc::Status)>) override;
      void DeleteEmployee(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response, std::function<void(::grpc::Status)>) override;
      void ListOfAnEmployeeBills(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* AsyncListEmployeeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* PrepareAsyncListEmployeeRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Employee>* AsyncGetEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Employee>* PrepareAsyncGetEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* AsyncCreateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* PrepareAsyncCreateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* AsyncUpdateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* PrepareAsyncUpdateEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* AsyncDeleteEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* PrepareAsyncDeleteEmployeeRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* AsyncListOfAnEmployeeBillsRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* PrepareAsyncListOfAnEmployeeBillsRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListEmployee_;
    const ::grpc::internal::RpcMethod rpcmethod_GetEmployee_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateEmployee_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateEmployee_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteEmployee_;
    const ::grpc::internal::RpcMethod rpcmethod_ListOfAnEmployeeBills_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ListEmployee(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response);
    virtual ::grpc::Status GetEmployee(::grpc::ServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Models::Employee* response);
    virtual ::grpc::Status CreateEmployee(::grpc::ServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response);
    virtual ::grpc::Status UpdateEmployee(::grpc::ServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response);
    virtual ::grpc::Status DeleteEmployee(::grpc::ServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response);
    virtual ::grpc::Status ListOfAnEmployeeBills(::grpc::ServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListEmployee() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListEmployee(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListEmployee(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetEmployee() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Employee* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEmployee(::grpc::ServerContext* context, ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Models::Employee>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateEmployee() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateEmployee(::grpc::ServerContext* context, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateEmployee() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_UpdateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateEmployee(::grpc::ServerContext* context, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteEmployee() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteEmployee(::grpc::ServerContext* context, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListOfAnEmployeeBills : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListOfAnEmployeeBills() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_ListOfAnEmployeeBills() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListOfAnEmployeeBills(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListOfAnEmployeeBills(::grpc::ServerContext* context, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListEmployee<WithAsyncMethod_GetEmployee<WithAsyncMethod_CreateEmployee<WithAsyncMethod_UpdateEmployee<WithAsyncMethod_DeleteEmployee<WithAsyncMethod_ListOfAnEmployeeBills<Service > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListEmployee() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* response) { return this->ListEmployee(context, request, response); }));}
    void SetMessageAllocatorFor_ListEmployee(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListEmployee(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetEmployee() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest, ::HyperNovaLabs::Api::Protos::Models::Employee>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Models::Employee* response) { return this->GetEmployee(context, request, response); }));}
    void SetMessageAllocatorFor_GetEmployee(
        ::grpc::MessageAllocator< ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest, ::HyperNovaLabs::Api::Protos::Models::Employee>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest, ::HyperNovaLabs::Api::Protos::Models::Employee>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Employee* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Employee* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateEmployee() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* response) { return this->CreateEmployee(context, request, response); }));}
    void SetMessageAllocatorFor_CreateEmployee(
        ::grpc::MessageAllocator< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateEmployee() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* response) { return this->UpdateEmployee(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateEmployee(
        ::grpc::MessageAllocator< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteEmployee() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* request, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* response) { return this->DeleteEmployee(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteEmployee(
        ::grpc::MessageAllocator< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListOfAnEmployeeBills : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListOfAnEmployeeBills() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* request, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* response) { return this->ListOfAnEmployeeBills(context, request, response); }));}
    void SetMessageAllocatorFor_ListOfAnEmployeeBills(
        ::grpc::MessageAllocator< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListOfAnEmployeeBills() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListOfAnEmployeeBills(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListOfAnEmployeeBills(
      ::grpc::CallbackServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListEmployee<WithCallbackMethod_GetEmployee<WithCallbackMethod_CreateEmployee<WithCallbackMethod_UpdateEmployee<WithCallbackMethod_DeleteEmployee<WithCallbackMethod_ListOfAnEmployeeBills<Service > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListEmployee() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListEmployee(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetEmployee() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Employee* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateEmployee() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateEmployee() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_UpdateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteEmployee() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListOfAnEmployeeBills : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListOfAnEmployeeBills() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_ListOfAnEmployeeBills() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListOfAnEmployeeBills(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListEmployee() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListEmployee(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListEmployee(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetEmployee() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Employee* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEmployee(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateEmployee() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_CreateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateEmployee(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateEmployee() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_UpdateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateEmployee(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteEmployee() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DeleteEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteEmployee(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListOfAnEmployeeBills : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListOfAnEmployeeBills() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_ListOfAnEmployeeBills() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListOfAnEmployeeBills(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListOfAnEmployeeBills(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListEmployee() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListEmployee(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListEmployee(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetEmployee() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetEmployee(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Employee* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateEmployee() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateEmployee(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateEmployee() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateEmployee(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteEmployee() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteEmployee(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteEmployee(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListOfAnEmployeeBills : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListOfAnEmployeeBills() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListOfAnEmployeeBills(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListOfAnEmployeeBills() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListOfAnEmployeeBills(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListOfAnEmployeeBills(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListEmployee() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* streamer) {
                       return this->StreamedListEmployee(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListEmployee(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListEmployee(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::HyperNovaLabs::Api::Protos::Services::ListEmployeeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetEmployee() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest, ::HyperNovaLabs::Api::Protos::Models::Employee>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest, ::HyperNovaLabs::Api::Protos::Models::Employee>* streamer) {
                       return this->StreamedGetEmployee(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Employee* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetEmployee(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HyperNovaLabs::Api::Protos::Services::GetEmployeeRequest,::HyperNovaLabs::Api::Protos::Models::Employee>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateEmployee() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* streamer) {
                       return this->StreamedCreateEmployee(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateEmployee(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HyperNovaLabs::Api::Protos::Services::CreateEmployeeRequest,::HyperNovaLabs::Api::Protos::Services::CreateEmployeeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateEmployee() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* streamer) {
                       return this->StreamedUpdateEmployee(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateEmployee(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeRequest,::HyperNovaLabs::Api::Protos::Services::UpdateEmployeeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteEmployee : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteEmployee() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* streamer) {
                       return this->StreamedDeleteEmployee(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteEmployee() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteEmployee(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteEmployee(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeRequest,::HyperNovaLabs::Api::Protos::Services::DeleteEmployeeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListOfAnEmployeeBills : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListOfAnEmployeeBills() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* streamer) {
                       return this->StreamedListOfAnEmployeeBills(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListOfAnEmployeeBills() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListOfAnEmployeeBills(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListOfAnEmployeeBills(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillRequest,::HyperNovaLabs::Api::Protos::Services::ListOfAnEmployeesBillResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListEmployee<WithStreamedUnaryMethod_GetEmployee<WithStreamedUnaryMethod_CreateEmployee<WithStreamedUnaryMethod_UpdateEmployee<WithStreamedUnaryMethod_DeleteEmployee<WithStreamedUnaryMethod_ListOfAnEmployeeBills<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListEmployee<WithStreamedUnaryMethod_GetEmployee<WithStreamedUnaryMethod_CreateEmployee<WithStreamedUnaryMethod_UpdateEmployee<WithStreamedUnaryMethod_DeleteEmployee<WithStreamedUnaryMethod_ListOfAnEmployeeBills<Service > > > > > > StreamedService;
};

}  // namespace Services
}  // namespace Protos
}  // namespace Api
}  // namespace HyperNovaLabs


#endif  // GRPC_EmployeeService_2eproto__INCLUDED
