// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ExpenseReportService.proto
#ifndef GRPC_ExpenseReportService_2eproto__INCLUDED
#define GRPC_ExpenseReportService_2eproto__INCLUDED

#include "ExpenseReportService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace HyperNovaLabs {
namespace Api {
namespace Protos {
namespace Services {

class ExpenseReportService final {
 public:
  static constexpr char const* service_full_name() {
    return "HyperNovaLabs.Api.Protos.Services.ExpenseReportService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>> AsyncListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>>(AsyncListBillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>> PrepareAsyncListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>>(PrepareAsyncListBillRaw(context, request, cq));
    }
    virtual ::grpc::Status GetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::HyperNovaLabs::Api::Protos::Models::Bill* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Bill>> AsyncGetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Bill>>(AsyncGetBillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Bill>> PrepareAsyncGetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Bill>>(PrepareAsyncGetBillRaw(context, request, cq));
    }
    virtual ::grpc::Status CreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>> AsyncCreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>>(AsyncCreateBillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>> PrepareAsyncCreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>>(PrepareAsyncCreateBillRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* request, ::HyperNovaLabs::Api::Protos::Models::Bill* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* request, ::HyperNovaLabs::Api::Protos::Models::Bill* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* AsyncListBillRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* PrepareAsyncListBillRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Bill>* AsyncGetBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Models::Bill>* PrepareAsyncGetBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* AsyncCreateBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* PrepareAsyncCreateBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>> AsyncListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>>(AsyncListBillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>> PrepareAsyncListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>>(PrepareAsyncListBillRaw(context, request, cq));
    }
    ::grpc::Status GetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::HyperNovaLabs::Api::Protos::Models::Bill* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Bill>> AsyncGetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Bill>>(AsyncGetBillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Bill>> PrepareAsyncGetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Bill>>(PrepareAsyncGetBillRaw(context, request, cq));
    }
    ::grpc::Status CreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>> AsyncCreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>>(AsyncCreateBillRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>> PrepareAsyncCreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>>(PrepareAsyncCreateBillRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response, std::function<void(::grpc::Status)>) override;
      void ListBill(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* request, ::HyperNovaLabs::Api::Protos::Models::Bill* response, std::function<void(::grpc::Status)>) override;
      void GetBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* request, ::HyperNovaLabs::Api::Protos::Models::Bill* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateBill(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* AsyncListBillRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* PrepareAsyncListBillRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Bill>* AsyncGetBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Models::Bill>* PrepareAsyncGetBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* AsyncCreateBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* PrepareAsyncCreateBillRaw(::grpc::ClientContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ListBill_;
    const ::grpc::internal::RpcMethod rpcmethod_GetBill_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateBill_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ListBill(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response);
    virtual ::grpc::Status GetBill(::grpc::ServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* request, ::HyperNovaLabs::Api::Protos::Models::Bill* response);
    virtual ::grpc::Status CreateBill(::grpc::ServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ListBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListBill() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ListBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListBill(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListBill(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBill() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Bill* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBill(::grpc::ServerContext* context, ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Models::Bill>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateBill() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_CreateBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateBill(::grpc::ServerContext* context, ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* request, ::grpc::ServerAsyncResponseWriter< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ListBill<WithAsyncMethod_GetBill<WithAsyncMethod_CreateBill<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ListBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListBill() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* response) { return this->ListBill(context, request, response); }));}
    void SetMessageAllocatorFor_ListBill(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListBill(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListBill(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetBill() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::GetBillRequest, ::HyperNovaLabs::Api::Protos::Models::Bill>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* request, ::HyperNovaLabs::Api::Protos::Models::Bill* response) { return this->GetBill(context, request, response); }));}
    void SetMessageAllocatorFor_GetBill(
        ::grpc::MessageAllocator< ::HyperNovaLabs::Api::Protos::Services::GetBillRequest, ::HyperNovaLabs::Api::Protos::Models::Bill>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::GetBillRequest, ::HyperNovaLabs::Api::Protos::Models::Bill>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Bill* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBill(
      ::grpc::CallbackServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Bill* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateBill() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* request, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* response) { return this->CreateBill(context, request, response); }));}
    void SetMessageAllocatorFor_CreateBill(
        ::grpc::MessageAllocator< ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateBill(
      ::grpc::CallbackServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ListBill<WithCallbackMethod_GetBill<WithCallbackMethod_CreateBill<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ListBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListBill() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ListBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListBill(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBill() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Bill* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateBill() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_CreateBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListBill() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ListBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListBill(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListBill(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBill() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Bill* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBill(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateBill() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_CreateBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateBill(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListBill() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListBill(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListBill(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListBill(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetBill() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBill(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Bill* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBill(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateBill() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateBill(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateBill(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListBill() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* streamer) {
                       return this->StreamedListBill(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListBill(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListBill(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::HyperNovaLabs::Api::Protos::Services::ListBillResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBill() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::HyperNovaLabs::Api::Protos::Services::GetBillRequest, ::HyperNovaLabs::Api::Protos::Models::Bill>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::HyperNovaLabs::Api::Protos::Services::GetBillRequest, ::HyperNovaLabs::Api::Protos::Models::Bill>* streamer) {
                       return this->StreamedGetBill(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* /*request*/, ::HyperNovaLabs::Api::Protos::Models::Bill* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBill(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HyperNovaLabs::Api::Protos::Services::GetBillRequest,::HyperNovaLabs::Api::Protos::Models::Bill>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateBill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateBill() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* streamer) {
                       return this->StreamedCreateBill(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateBill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateBill(::grpc::ServerContext* /*context*/, const ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* /*request*/, ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateBill(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest,::HyperNovaLabs::Api::Protos::Services::CreateBillResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ListBill<WithStreamedUnaryMethod_GetBill<WithStreamedUnaryMethod_CreateBill<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ListBill<WithStreamedUnaryMethod_GetBill<WithStreamedUnaryMethod_CreateBill<Service > > > StreamedService;
};

}  // namespace Services
}  // namespace Protos
}  // namespace Api
}  // namespace HyperNovaLabs


#endif  // GRPC_ExpenseReportService_2eproto__INCLUDED
