// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExpenseReportService.proto

#include "ExpenseReportService.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace HyperNovaLabs {
namespace Api {
namespace Protos {
namespace Services {
constexpr ListBillResponse::ListBillResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : bills_(){}
struct ListBillResponseDefaultTypeInternal {
  constexpr ListBillResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ListBillResponseDefaultTypeInternal() {}
  union {
    ListBillResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ListBillResponseDefaultTypeInternal _ListBillResponse_default_instance_;
constexpr GetBillRequest::GetBillRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : bill_id_(PROTOBUF_LONGLONG(0)){}
struct GetBillRequestDefaultTypeInternal {
  constexpr GetBillRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~GetBillRequestDefaultTypeInternal() {}
  union {
    GetBillRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT GetBillRequestDefaultTypeInternal _GetBillRequest_default_instance_;
constexpr CreateBillResquest::CreateBillResquest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : bill_(nullptr){}
struct CreateBillResquestDefaultTypeInternal {
  constexpr CreateBillResquestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CreateBillResquestDefaultTypeInternal() {}
  union {
    CreateBillResquest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CreateBillResquestDefaultTypeInternal _CreateBillResquest_default_instance_;
constexpr CreateBillResponse::CreateBillResponse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : errors_()
  , bill_(nullptr)
  , has_error_(false){}
struct CreateBillResponseDefaultTypeInternal {
  constexpr CreateBillResponseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CreateBillResponseDefaultTypeInternal() {}
  union {
    CreateBillResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CreateBillResponseDefaultTypeInternal _CreateBillResponse_default_instance_;
}  // namespace Services
}  // namespace Protos
}  // namespace Api
}  // namespace HyperNovaLabs
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ExpenseReportService_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ExpenseReportService_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ExpenseReportService_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ExpenseReportService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::ListBillResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::ListBillResponse, bills_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::GetBillRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::GetBillRequest, bill_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::CreateBillResquest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::CreateBillResquest, bill_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::CreateBillResponse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::CreateBillResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::CreateBillResponse, bill_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::CreateBillResponse, has_error_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Services::CreateBillResponse, errors_),
  0,
  ~0u,
  ~0u,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::HyperNovaLabs::Api::Protos::Services::ListBillResponse)},
  { 6, -1, sizeof(::HyperNovaLabs::Api::Protos::Services::GetBillRequest)},
  { 12, -1, sizeof(::HyperNovaLabs::Api::Protos::Services::CreateBillResquest)},
  { 18, 26, sizeof(::HyperNovaLabs::Api::Protos::Services::CreateBillResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::HyperNovaLabs::Api::Protos::Services::_ListBillResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::HyperNovaLabs::Api::Protos::Services::_GetBillRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::HyperNovaLabs::Api::Protos::Services::_CreateBillResquest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::HyperNovaLabs::Api::Protos::Services::_CreateBillResponse_default_instance_),
};

const char descriptor_table_protodef_ExpenseReportService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032ExpenseReportService.proto\022!HyperNovaL"
  "abs.Api.Protos.Services\032\034google/api/anno"
  "tations.proto\032\033google/protobuf/empty.pro"
  "to\032\021Models/Bill.proto\"H\n\020ListBillRespons"
  "e\0224\n\005bills\030\001 \003(\0132%.HyperNovaLabs.Api.Pro"
  "tos.Models.Bill\"!\n\016GetBillRequest\022\017\n\007bil"
  "l_id\030\001 \001(\003\"I\n\022CreateBillResquest\0223\n\004bill"
  "\030\001 \001(\0132%.HyperNovaLabs.Api.Protos.Models"
  ".Bill\"z\n\022CreateBillResponse\0228\n\004bill\030\001 \001("
  "\0132%.HyperNovaLabs.Api.Protos.Models.Bill"
  "H\000\210\001\001\022\021\n\thas_error\030\002 \001(\010\022\016\n\006errors\030\003 \003(\t"
  "B\007\n\005_bill2\233\003\n\024ExpenseReportService\022j\n\010Li"
  "stBill\022\026.google.protobuf.Empty\0323.HyperNo"
  "vaLabs.Api.Protos.Services.ListBillRespo"
  "nse\"\021\202\323\344\223\002\013\022\t/api/bill\022\200\001\n\007GetBill\0221.Hyp"
  "erNovaLabs.Api.Protos.Services.GetBillRe"
  "quest\032%.HyperNovaLabs.Api.Protos.Models."
  "Bill\"\033\202\323\344\223\002\025\022\023/api/bill/{bill_id}\022\223\001\n\nCr"
  "eateBill\0225.HyperNovaLabs.Api.Protos.Serv"
  "ices.CreateBillResquest\0325.HyperNovaLabs."
  "Api.Protos.Services.CreateBillResponse\"\027"
  "\202\323\344\223\002\021\"\t/api/bill:\004billB\003\370\001\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ExpenseReportService_2eproto_deps[3] = {
  &::descriptor_table_Models_2fBill_2eproto,
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ExpenseReportService_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ExpenseReportService_2eproto = {
  false, false, 876, descriptor_table_protodef_ExpenseReportService_2eproto, "ExpenseReportService.proto", 
  &descriptor_table_ExpenseReportService_2eproto_once, descriptor_table_ExpenseReportService_2eproto_deps, 3, 4,
  schemas, file_default_instances, TableStruct_ExpenseReportService_2eproto::offsets,
  file_level_metadata_ExpenseReportService_2eproto, file_level_enum_descriptors_ExpenseReportService_2eproto, file_level_service_descriptors_ExpenseReportService_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_ExpenseReportService_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_ExpenseReportService_2eproto);
  return descriptor_table_ExpenseReportService_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ExpenseReportService_2eproto(&descriptor_table_ExpenseReportService_2eproto);
namespace HyperNovaLabs {
namespace Api {
namespace Protos {
namespace Services {

// ===================================================================

class ListBillResponse::_Internal {
 public:
};

void ListBillResponse::clear_bills() {
  bills_.Clear();
}
ListBillResponse::ListBillResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  bills_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
}
ListBillResponse::ListBillResponse(const ListBillResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      bills_(from.bills_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
}

void ListBillResponse::SharedCtor() {
}

ListBillResponse::~ListBillResponse() {
  // @@protoc_insertion_point(destructor:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ListBillResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ListBillResponse::ArenaDtor(void* object) {
  ListBillResponse* _this = reinterpret_cast< ListBillResponse* >(object);
  (void)_this;
}
void ListBillResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ListBillResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ListBillResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bills_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ListBillResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .HyperNovaLabs.Api.Protos.Models.Bill bills = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_bills(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ListBillResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .HyperNovaLabs.Api.Protos.Models.Bill bills = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_bills_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_bills(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  return target;
}

size_t ListBillResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .HyperNovaLabs.Api.Protos.Models.Bill bills = 1;
  total_size += 1UL * this->_internal_bills_size();
  for (const auto& msg : this->bills_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ListBillResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ListBillResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ListBillResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
    MergeFrom(*source);
  }
}

void ListBillResponse::MergeFrom(const ListBillResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bills_.MergeFrom(from.bills_);
}

void ListBillResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListBillResponse::CopyFrom(const ListBillResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HyperNovaLabs.Api.Protos.Services.ListBillResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListBillResponse::IsInitialized() const {
  return true;
}

void ListBillResponse::InternalSwap(ListBillResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  bills_.InternalSwap(&other->bills_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ListBillResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class GetBillRequest::_Internal {
 public:
};

GetBillRequest::GetBillRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
}
GetBillRequest::GetBillRequest(const GetBillRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  bill_id_ = from.bill_id_;
  // @@protoc_insertion_point(copy_constructor:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
}

void GetBillRequest::SharedCtor() {
bill_id_ = PROTOBUF_LONGLONG(0);
}

GetBillRequest::~GetBillRequest() {
  // @@protoc_insertion_point(destructor:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GetBillRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GetBillRequest::ArenaDtor(void* object) {
  GetBillRequest* _this = reinterpret_cast< GetBillRequest* >(object);
  (void)_this;
}
void GetBillRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GetBillRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GetBillRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bill_id_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetBillRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int64 bill_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          bill_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GetBillRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 bill_id = 1;
  if (this->bill_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_bill_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  return target;
}

size_t GetBillRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 bill_id = 1;
  if (this->bill_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_bill_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetBillRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const GetBillRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GetBillRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
    MergeFrom(*source);
  }
}

void GetBillRequest::MergeFrom(const GetBillRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.bill_id() != 0) {
    _internal_set_bill_id(from._internal_bill_id());
  }
}

void GetBillRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetBillRequest::CopyFrom(const GetBillRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HyperNovaLabs.Api.Protos.Services.GetBillRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetBillRequest::IsInitialized() const {
  return true;
}

void GetBillRequest::InternalSwap(GetBillRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(bill_id_, other->bill_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetBillRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class CreateBillResquest::_Internal {
 public:
  static const ::HyperNovaLabs::Api::Protos::Models::Bill& bill(const CreateBillResquest* msg);
};

const ::HyperNovaLabs::Api::Protos::Models::Bill&
CreateBillResquest::_Internal::bill(const CreateBillResquest* msg) {
  return *msg->bill_;
}
void CreateBillResquest::clear_bill() {
  if (GetArena() == nullptr && bill_ != nullptr) {
    delete bill_;
  }
  bill_ = nullptr;
}
CreateBillResquest::CreateBillResquest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
}
CreateBillResquest::CreateBillResquest(const CreateBillResquest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_bill()) {
    bill_ = new ::HyperNovaLabs::Api::Protos::Models::Bill(*from.bill_);
  } else {
    bill_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
}

void CreateBillResquest::SharedCtor() {
bill_ = nullptr;
}

CreateBillResquest::~CreateBillResquest() {
  // @@protoc_insertion_point(destructor:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CreateBillResquest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete bill_;
}

void CreateBillResquest::ArenaDtor(void* object) {
  CreateBillResquest* _this = reinterpret_cast< CreateBillResquest* >(object);
  (void)_this;
}
void CreateBillResquest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CreateBillResquest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CreateBillResquest::Clear() {
// @@protoc_insertion_point(message_clear_start:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && bill_ != nullptr) {
    delete bill_;
  }
  bill_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateBillResquest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .HyperNovaLabs.Api.Protos.Models.Bill bill = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_bill(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CreateBillResquest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .HyperNovaLabs.Api.Protos.Models.Bill bill = 1;
  if (this->has_bill()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::bill(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  return target;
}

size_t CreateBillResquest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .HyperNovaLabs.Api.Protos.Models.Bill bill = 1;
  if (this->has_bill()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *bill_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateBillResquest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateBillResquest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CreateBillResquest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
    MergeFrom(*source);
  }
}

void CreateBillResquest::MergeFrom(const CreateBillResquest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_bill()) {
    _internal_mutable_bill()->::HyperNovaLabs::Api::Protos::Models::Bill::MergeFrom(from._internal_bill());
  }
}

void CreateBillResquest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateBillResquest::CopyFrom(const CreateBillResquest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResquest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateBillResquest::IsInitialized() const {
  return true;
}

void CreateBillResquest::InternalSwap(CreateBillResquest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(bill_, other->bill_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateBillResquest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class CreateBillResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<CreateBillResponse>()._has_bits_);
  static const ::HyperNovaLabs::Api::Protos::Models::Bill& bill(const CreateBillResponse* msg);
  static void set_has_bill(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::HyperNovaLabs::Api::Protos::Models::Bill&
CreateBillResponse::_Internal::bill(const CreateBillResponse* msg) {
  return *msg->bill_;
}
void CreateBillResponse::clear_bill() {
  if (GetArena() == nullptr && bill_ != nullptr) {
    delete bill_;
  }
  bill_ = nullptr;
  _has_bits_[0] &= ~0x00000001u;
}
CreateBillResponse::CreateBillResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  errors_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
}
CreateBillResponse::CreateBillResponse(const CreateBillResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      errors_(from.errors_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_bill()) {
    bill_ = new ::HyperNovaLabs::Api::Protos::Models::Bill(*from.bill_);
  } else {
    bill_ = nullptr;
  }
  has_error_ = from.has_error_;
  // @@protoc_insertion_point(copy_constructor:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
}

void CreateBillResponse::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&bill_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&has_error_) -
    reinterpret_cast<char*>(&bill_)) + sizeof(has_error_));
}

CreateBillResponse::~CreateBillResponse() {
  // @@protoc_insertion_point(destructor:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CreateBillResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete bill_;
}

void CreateBillResponse::ArenaDtor(void* object) {
  CreateBillResponse* _this = reinterpret_cast< CreateBillResponse* >(object);
  (void)_this;
}
void CreateBillResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CreateBillResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CreateBillResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  errors_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    if (GetArena() == nullptr && bill_ != nullptr) {
      delete bill_;
    }
    bill_ = nullptr;
  }
  has_error_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CreateBillResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .HyperNovaLabs.Api.Protos.Models.Bill bill = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_bill(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool has_error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          has_error_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated string errors = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_errors();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "HyperNovaLabs.Api.Protos.Services.CreateBillResponse.errors"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CreateBillResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .HyperNovaLabs.Api.Protos.Models.Bill bill = 1;
  if (_internal_has_bill()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::bill(this), target, stream);
  }

  // bool has_error = 2;
  if (this->has_error() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_has_error(), target);
  }

  // repeated string errors = 3;
  for (int i = 0, n = this->_internal_errors_size(); i < n; i++) {
    const auto& s = this->_internal_errors(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "HyperNovaLabs.Api.Protos.Services.CreateBillResponse.errors");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  return target;
}

size_t CreateBillResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string errors = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(errors_.size());
  for (int i = 0, n = errors_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      errors_.Get(i));
  }

  // .HyperNovaLabs.Api.Protos.Models.Bill bill = 1;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *bill_);
  }

  // bool has_error = 2;
  if (this->has_error() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateBillResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateBillResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CreateBillResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
    MergeFrom(*source);
  }
}

void CreateBillResponse::MergeFrom(const CreateBillResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  errors_.MergeFrom(from.errors_);
  if (from._internal_has_bill()) {
    _internal_mutable_bill()->::HyperNovaLabs::Api::Protos::Models::Bill::MergeFrom(from._internal_bill());
  }
  if (from.has_error() != 0) {
    _internal_set_has_error(from._internal_has_error());
  }
}

void CreateBillResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateBillResponse::CopyFrom(const CreateBillResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HyperNovaLabs.Api.Protos.Services.CreateBillResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateBillResponse::IsInitialized() const {
  return true;
}

void CreateBillResponse::InternalSwap(CreateBillResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  errors_.InternalSwap(&other->errors_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CreateBillResponse, has_error_)
      + sizeof(CreateBillResponse::has_error_)
      - PROTOBUF_FIELD_OFFSET(CreateBillResponse, bill_)>(
          reinterpret_cast<char*>(&bill_),
          reinterpret_cast<char*>(&other->bill_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CreateBillResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Services
}  // namespace Protos
}  // namespace Api
}  // namespace HyperNovaLabs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HyperNovaLabs::Api::Protos::Services::ListBillResponse* Arena::CreateMaybeMessage< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HyperNovaLabs::Api::Protos::Services::ListBillResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::HyperNovaLabs::Api::Protos::Services::GetBillRequest* Arena::CreateMaybeMessage< ::HyperNovaLabs::Api::Protos::Services::GetBillRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HyperNovaLabs::Api::Protos::Services::GetBillRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest* Arena::CreateMaybeMessage< ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HyperNovaLabs::Api::Protos::Services::CreateBillResquest >(arena);
}
template<> PROTOBUF_NOINLINE ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse* Arena::CreateMaybeMessage< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HyperNovaLabs::Api::Protos::Services::CreateBillResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
