version: '3.4'

services:
  hypernovalabs.native.backend:
    image: technical-test/hypernovalabs.native.backend
    container_name: technical-test/hypernovalabs.native.backend
    build:
      context: HyperNovaLabsNativeBackend
      dockerfile: Dockerfile
    ports:
      - "50051:50051"

  hypernovalabs.web:
    image: technical-test/hypernovalabs.web
    container_name: technical-test/hypernovalabs.web
    build:
      context: HyperNovaLabs
      dockerfile: Dockerfile
    ports:
      - "5965:80"
