version: '3.4'

services:
  hypernovalabs.api:
    image: ${DOCKER_REGISTRY-}hypernovalabsapi
    build:
      context: .
      dockerfile: HyperNovaLabs.Api/Dockerfile
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest