// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/api/http.proto

#include "google/api/http.pb.h"
#include "google/api/http.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace google {
namespace api {

} // namespace google
} // namespace api

