// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Models/Bill.proto

#include "Models/Bill.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace HyperNovaLabs {
namespace Api {
namespace Protos {
namespace Models {
constexpr Bill::Bill(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : bill_descriptions_()
  , bill_concept_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , approved_by_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , date_from_(nullptr)
  , date_to_(nullptr)
  , employee_(nullptr){}
struct BillDefaultTypeInternal {
  constexpr BillDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~BillDefaultTypeInternal() {}
  union {
    Bill _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT BillDefaultTypeInternal _Bill_default_instance_;
}  // namespace Models
}  // namespace Protos
}  // namespace Api
}  // namespace HyperNovaLabs
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Models_2fBill_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Models_2fBill_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Models_2fBill_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Models_2fBill_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Models::Bill, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Models::Bill, bill_concept_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Models::Bill, date_from_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Models::Bill, date_to_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Models::Bill, approved_by_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Models::Bill, employee_),
  PROTOBUF_FIELD_OFFSET(::HyperNovaLabs::Api::Protos::Models::Bill, bill_descriptions_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::HyperNovaLabs::Api::Protos::Models::Bill)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::HyperNovaLabs::Api::Protos::Models::_Bill_default_instance_),
};

const char descriptor_table_protodef_Models_2fBill_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021Models/Bill.proto\022\037HyperNovaLabs.Api.P"
  "rotos.Models\032\037google/protobuf/timestamp."
  "proto\032\034Models/BillDescription.proto\032\025Mod"
  "els/Employee.proto\"\227\002\n\004Bill\022\024\n\014bill_conc"
  "ept\030\001 \001(\t\022-\n\tdate_from\030\002 \001(\0132\032.google.pr"
  "otobuf.Timestamp\022+\n\007date_to\030\003 \001(\0132\032.goog"
  "le.protobuf.Timestamp\022\023\n\013approved_by\030\004 \001"
  "(\t\022;\n\010employee\030\005 \001(\0132).HyperNovaLabs.Api"
  ".Protos.Models.Employee\022K\n\021bill_descript"
  "ions\030\006 \003(\01320.HyperNovaLabs.Api.Protos.Mo"
  "dels.BillDescriptionB\003\370\001\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Models_2fBill_2eproto_deps[3] = {
  &::descriptor_table_Models_2fBillDescription_2eproto,
  &::descriptor_table_Models_2fEmployee_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Models_2fBill_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Models_2fBill_2eproto = {
  false, false, 433, descriptor_table_protodef_Models_2fBill_2eproto, "Models/Bill.proto", 
  &descriptor_table_Models_2fBill_2eproto_once, descriptor_table_Models_2fBill_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_Models_2fBill_2eproto::offsets,
  file_level_metadata_Models_2fBill_2eproto, file_level_enum_descriptors_Models_2fBill_2eproto, file_level_service_descriptors_Models_2fBill_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_Models_2fBill_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Models_2fBill_2eproto);
  return descriptor_table_Models_2fBill_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Models_2fBill_2eproto(&descriptor_table_Models_2fBill_2eproto);
namespace HyperNovaLabs {
namespace Api {
namespace Protos {
namespace Models {

// ===================================================================

class Bill::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::Timestamp& date_from(const Bill* msg);
  static const PROTOBUF_NAMESPACE_ID::Timestamp& date_to(const Bill* msg);
  static const ::HyperNovaLabs::Api::Protos::Models::Employee& employee(const Bill* msg);
};

const PROTOBUF_NAMESPACE_ID::Timestamp&
Bill::_Internal::date_from(const Bill* msg) {
  return *msg->date_from_;
}
const PROTOBUF_NAMESPACE_ID::Timestamp&
Bill::_Internal::date_to(const Bill* msg) {
  return *msg->date_to_;
}
const ::HyperNovaLabs::Api::Protos::Models::Employee&
Bill::_Internal::employee(const Bill* msg) {
  return *msg->employee_;
}
void Bill::clear_date_from() {
  if (GetArena() == nullptr && date_from_ != nullptr) {
    delete date_from_;
  }
  date_from_ = nullptr;
}
void Bill::clear_date_to() {
  if (GetArena() == nullptr && date_to_ != nullptr) {
    delete date_to_;
  }
  date_to_ = nullptr;
}
void Bill::clear_employee() {
  if (GetArena() == nullptr && employee_ != nullptr) {
    delete employee_;
  }
  employee_ = nullptr;
}
void Bill::clear_bill_descriptions() {
  bill_descriptions_.Clear();
}
Bill::Bill(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  bill_descriptions_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:HyperNovaLabs.Api.Protos.Models.Bill)
}
Bill::Bill(const Bill& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      bill_descriptions_(from.bill_descriptions_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  bill_concept_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_bill_concept().empty()) {
    bill_concept_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_bill_concept(), 
      GetArena());
  }
  approved_by_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_approved_by().empty()) {
    approved_by_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_approved_by(), 
      GetArena());
  }
  if (from._internal_has_date_from()) {
    date_from_ = new PROTOBUF_NAMESPACE_ID::Timestamp(*from.date_from_);
  } else {
    date_from_ = nullptr;
  }
  if (from._internal_has_date_to()) {
    date_to_ = new PROTOBUF_NAMESPACE_ID::Timestamp(*from.date_to_);
  } else {
    date_to_ = nullptr;
  }
  if (from._internal_has_employee()) {
    employee_ = new ::HyperNovaLabs::Api::Protos::Models::Employee(*from.employee_);
  } else {
    employee_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:HyperNovaLabs.Api.Protos.Models.Bill)
}

void Bill::SharedCtor() {
bill_concept_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
approved_by_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&date_from_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&employee_) -
    reinterpret_cast<char*>(&date_from_)) + sizeof(employee_));
}

Bill::~Bill() {
  // @@protoc_insertion_point(destructor:HyperNovaLabs.Api.Protos.Models.Bill)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Bill::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  bill_concept_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  approved_by_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete date_from_;
  if (this != internal_default_instance()) delete date_to_;
  if (this != internal_default_instance()) delete employee_;
}

void Bill::ArenaDtor(void* object) {
  Bill* _this = reinterpret_cast< Bill* >(object);
  (void)_this;
}
void Bill::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Bill::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Bill::Clear() {
// @@protoc_insertion_point(message_clear_start:HyperNovaLabs.Api.Protos.Models.Bill)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bill_descriptions_.Clear();
  bill_concept_.ClearToEmpty();
  approved_by_.ClearToEmpty();
  if (GetArena() == nullptr && date_from_ != nullptr) {
    delete date_from_;
  }
  date_from_ = nullptr;
  if (GetArena() == nullptr && date_to_ != nullptr) {
    delete date_to_;
  }
  date_to_ = nullptr;
  if (GetArena() == nullptr && employee_ != nullptr) {
    delete employee_;
  }
  employee_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Bill::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string bill_concept = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_bill_concept();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "HyperNovaLabs.Api.Protos.Models.Bill.bill_concept"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp date_from = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_date_from(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp date_to = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_date_to(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string approved_by = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_approved_by();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "HyperNovaLabs.Api.Protos.Models.Bill.approved_by"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .HyperNovaLabs.Api.Protos.Models.Employee employee = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_employee(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .HyperNovaLabs.Api.Protos.Models.BillDescription bill_descriptions = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_bill_descriptions(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Bill::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HyperNovaLabs.Api.Protos.Models.Bill)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string bill_concept = 1;
  if (this->bill_concept().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_bill_concept().data(), static_cast<int>(this->_internal_bill_concept().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "HyperNovaLabs.Api.Protos.Models.Bill.bill_concept");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_bill_concept(), target);
  }

  // .google.protobuf.Timestamp date_from = 2;
  if (this->has_date_from()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::date_from(this), target, stream);
  }

  // .google.protobuf.Timestamp date_to = 3;
  if (this->has_date_to()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::date_to(this), target, stream);
  }

  // string approved_by = 4;
  if (this->approved_by().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_approved_by().data(), static_cast<int>(this->_internal_approved_by().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "HyperNovaLabs.Api.Protos.Models.Bill.approved_by");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_approved_by(), target);
  }

  // .HyperNovaLabs.Api.Protos.Models.Employee employee = 5;
  if (this->has_employee()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::employee(this), target, stream);
  }

  // repeated .HyperNovaLabs.Api.Protos.Models.BillDescription bill_descriptions = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_bill_descriptions_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_bill_descriptions(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HyperNovaLabs.Api.Protos.Models.Bill)
  return target;
}

size_t Bill::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HyperNovaLabs.Api.Protos.Models.Bill)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .HyperNovaLabs.Api.Protos.Models.BillDescription bill_descriptions = 6;
  total_size += 1UL * this->_internal_bill_descriptions_size();
  for (const auto& msg : this->bill_descriptions_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string bill_concept = 1;
  if (this->bill_concept().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bill_concept());
  }

  // string approved_by = 4;
  if (this->approved_by().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_approved_by());
  }

  // .google.protobuf.Timestamp date_from = 2;
  if (this->has_date_from()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *date_from_);
  }

  // .google.protobuf.Timestamp date_to = 3;
  if (this->has_date_to()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *date_to_);
  }

  // .HyperNovaLabs.Api.Protos.Models.Employee employee = 5;
  if (this->has_employee()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *employee_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Bill::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HyperNovaLabs.Api.Protos.Models.Bill)
  GOOGLE_DCHECK_NE(&from, this);
  const Bill* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Bill>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HyperNovaLabs.Api.Protos.Models.Bill)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HyperNovaLabs.Api.Protos.Models.Bill)
    MergeFrom(*source);
  }
}

void Bill::MergeFrom(const Bill& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HyperNovaLabs.Api.Protos.Models.Bill)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bill_descriptions_.MergeFrom(from.bill_descriptions_);
  if (from.bill_concept().size() > 0) {
    _internal_set_bill_concept(from._internal_bill_concept());
  }
  if (from.approved_by().size() > 0) {
    _internal_set_approved_by(from._internal_approved_by());
  }
  if (from.has_date_from()) {
    _internal_mutable_date_from()->PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(from._internal_date_from());
  }
  if (from.has_date_to()) {
    _internal_mutable_date_to()->PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(from._internal_date_to());
  }
  if (from.has_employee()) {
    _internal_mutable_employee()->::HyperNovaLabs::Api::Protos::Models::Employee::MergeFrom(from._internal_employee());
  }
}

void Bill::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HyperNovaLabs.Api.Protos.Models.Bill)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Bill::CopyFrom(const Bill& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HyperNovaLabs.Api.Protos.Models.Bill)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Bill::IsInitialized() const {
  return true;
}

void Bill::InternalSwap(Bill* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  bill_descriptions_.InternalSwap(&other->bill_descriptions_);
  bill_concept_.Swap(&other->bill_concept_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  approved_by_.Swap(&other->approved_by_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Bill, employee_)
      + sizeof(Bill::employee_)
      - PROTOBUF_FIELD_OFFSET(Bill, date_from_)>(
          reinterpret_cast<char*>(&date_from_),
          reinterpret_cast<char*>(&other->date_from_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Bill::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Models
}  // namespace Protos
}  // namespace Api
}  // namespace HyperNovaLabs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HyperNovaLabs::Api::Protos::Models::Bill* Arena::CreateMaybeMessage< ::HyperNovaLabs::Api::Protos::Models::Bill >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HyperNovaLabs::Api::Protos::Models::Bill >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
