// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Models/Employee.proto

#include "Models/Employee.pb.h"
#include "Models/Employee.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace HyperNovaLabs {
namespace Api {
namespace Protos {
namespace Models {

} // namespace HyperNovaLabs
} // namespace Api
} // namespace Protos
} // namespace Models

